services:
  cuda-dev:
    image: morninbru/dev:cuda
    container_name: cuda_dev
    build:
      context: .
      dockerfile: Dockerfile.cuda
      args:
        USER: $USER
        CUDA_VERSION: "12.5.0"
        UBUNTU_VERSION: "22.04"
        CMAKE_VERSION: "3.30.0"
        LLVM_VERSION: "17"
        FZF_VERSION: "0.53.0"
        NVIM_VERSION: "0.10.0"
        PYTHON_VERSION: "3.12"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/$USER/workspace
