#!/usr/bin/env bash

if [[ "$1" == "--drun" ]]; then
  killall rofi ||
    rofi -show drun
elif [[ "$1" == "--calc" ]]; then
  killall rofi ||
    rofi \
      -show calc -modi calc \
      -no-show-match -no-sort -no-show-icons -no-fixed-num-lines \
      -theme-str '@import "~/.config/rofi/calc.rasi"' | wl-copy
elif [[ "$1" == "--bw" ]]; then
  killall rofi ||
    $HOME/.dotfiles/scripts/rofi/bw
fi
