#!/usr/bin/env bash

notify() {
  icons=("" "" "" "" "" "" "" "" "" "" "" "" "" "" "󰃠")
  value=$(brightnessctl g)
  pcent=$(echo $value \* 100 / 255 | bc)
  idx=$(echo $value \* ${#icons[@]} / 255 | bc)
  if [[ idx -ge ${#icons[@]} ]]; then
    idx=$((${#icons[@]} - 1))
  fi
  notify-send \
    -c brightness \
    -h string:x-canonical-private-synchronous:sys-notify \
    -h int:value:$pcent \
    -u low "${icons[$idx]} brightness" "$pcent%"
}

if [[ "$1" == "--inc" ]]; then
  brightnessctl set $2%+ && notify
elif [[ "$1" == "--dec" ]]; then
  brightnessctl set $2%- && notify
else
  notify
fi
