#!/usr/bin/env bash

player=org.mpris.MediaPlayer2.playerctld

if [[ "$1" == "--play-pause" ]]; then
  qdbus $player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
elif [[ "$1" == "--next" ]]; then
  qdbus $player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
elif [[ "$1" == "--prev" ]]; then
  qdbus $player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
fi
