# Env variables
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CACHE_HOME,$HOME/.cache
# env = XCURSOR_SIZE,16

env = ELECTRON_OZONE_PLATFORM_HINT,auto

# gtk
env = GDK_SCALE,1.25
env = GDK_BACKEND,wayland

# qt
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland 
env = CLUTTER_BACKEND,wayland 
# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
