#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "$1" == "--drun" ]]; then
  killall rofi ||
    rofi -show drun \
      -kb-row-left Left -kb-row-right Right \
      -kb-move-char-back Control+b -kb-move-char-forward Control+f
elif [[ "$1" == "--calc" ]]; then
  killall rofi ||
    rofi \
      -show calc -modi calc \
      -no-show-match -no-sort -no-show-icons -no-fixed-num-lines \
      -theme-str '@import "~/.config/rofi/calc.rasi"' | wl-copy
elif [[ "$1" == "--bw" ]]; then
  killall rofi || $SCRIPT_DIR/bw/bw.sh
elif [[ "$1" == "--pyfia" ]]; then
  killall rofi || $SCRIPT_DIR/pyfia/pyfia.sh
elif [[ "$1" == "--nerdicons" ]]; then
  killall rofi || $SCRIPT_DIR/nerdicons/nerdicons.sh
elif [[ "$1" == "--emojis" ]]; then
  killall rofi || killall rofimoji || $HOME/.local/bin/rofimoji --selector-args='
      -theme ~/.config/rofi/moji.rasi
      -kb-row-left Left -kb-row-right Right 
      -kb-move-char-back Control+b -kb-move-char-forward Control+f
    ' --hidden-descriptions -a type copy --max-recent 0
fi
