#!/usr/bin/env bash

bw_search() {
  local prompt=$(
    rofi -p "" -dmenu -no-fixed-num-lines -theme-str \
      'entry { 
        placeholder: "search bitwarden"; 
      } 
      inputbar { 
        children: [prompt, textbox-prompt-colon, entry];
      }'
  )
  if [ -z "$prompt" ]; then
    exit 1
  fi
  local items=$(
    BW_SESSION=$(pass bw_session) \
    BITWARDENCLI_APPDATA_DIR=$HOME/.bw/ \
    NODE_OPTIONS="--no-deprecation" \
      bw list items --search $prompt
  )
  if [[ $(jq -r '. | length' <<<$items) -eq 1 ]]; then
    (jq -r '.[].login.password' <<<$items) | tr -d '\n' | wl-copy
    local msg=$(
      jq -r '
        "name : " + .[].name + "\n  username : " + .[].login.username + "\n  password : <clipboard>"
      ' <<<$items
    )
    notify-send "bitwarden" "$msg"
  else
    local idx=$(
      echo $items |
        jq -r 'to_entries | .[] | .value.name + " -- " + .value.login.username' |
        rofi -p "" -dmenu -no-fixed-num-lines \
          -format i -theme-str \
          'entry { 
            placeholder: "search bitwarden"; 
          } 
          inputbar { 
            children: [prompt, textbox-prompt-colon, entry];
          }'
    )
    if [[ $idx -ge $(jq -r '. | length' <<<$items) ]]; then
      notify-send -u critical "bitwarden" "Invalid index"
      exit 1
    fi
    (jq -r ".[$idx].login.password" <<<$items) | tr -d '\n' | wl-copy
    local msg=$(
      jq -r ".[$idx]"'| 
        ("name : " + .name + "\n  username : " + .login.username + "\n  password : <clipboard>")
      ' <<<$items
    )
    notify-send "bitwarden" "$msg"
  fi
}

bw_search
