#!/usr/bin/env sh

# Get the current song playing
metadata=$(qdbus org.mpris.MediaPlayer2.playerctld /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata)

to_normal() {
  min=$(echo "$1 / 60 / 1000000" | bc)
  sec=$(echo "$1 / 1000000 % 60" | bc)
  printf "%02d:%02d" "$min" "$sec"
}

if [ -z "$metadata" ]; then
  printf ""
  exit 0
else
  player=$(qdbus org.mpris.MediaPlayer2.playerctld /org/mpris/MediaPlayer2 com.github.altdesktop.playerctld.PlayerNames | awk 'NR==1{print}')
  position=$(qdbus org.mpris.MediaPlayer2.playerctld /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Position)
  status=$(qdbus org.mpris.MediaPlayer2.playerctld /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus)

  title=$(echo "$metadata" | grep -oP 'title: \K.*$')
  artist=$(echo "$metadata" | grep -oP 'artist: \K.*$')
  album=$(echo "$metadata" | grep -oP 'album: \K.*$')

  length=$(echo "$metadata" | grep -oP 'length: \K.*$')
  length=$(to_normal "$length")
  position=$(to_normal "$position")

  picon=""
  if [ $(grep -c "firefox" <<< "$player") -gt 0 ]; then
    picon="󰈹"
  elif [ $(grep -c "mpv" <<< "$player") -gt 0 ]; then
    picon=""
  elif [ $(grep -c "spotify" <<< "$player") -gt 0 ]; then
    picon=""
  elif [ $(grep -c "spotifyd" <<< "$player") -gt 0 ]; then
    picon=""
  elif [ $(grep -c "vlc" <<< "$player") -gt 0 ]; then
    picon="󰕼"
  fi

  if [ "$status" = "Playing" ]; then
    sicon=""
  elif [ "$status" = "Paused" ]; then
    sicon=""
  fi

  printf "$picon  $sicon $position / $length\n.. $title\n.: $artist\n:: $album"
fi

