#!/usr/bin/env bash

help() {
  echo "Usage: $0 [args]"
  echo "  --procs: returns the top 10 processes by cpu usage"
  echo "  --temp: returns the cpu temperature"
}

if [[ $1 == "--procs" ]]; then

  ps -eo pcpu,cmd |
    grep -v '\[' |
    awk '
      NR>2 { 
        mem[$2]+=$1 
      } END {
        for(k in mem) 
          print k " " mem[k]
      };' |
    sort -rgk 2 |
    head -n 10 |
    awk '{ 
          split($1, proc, "/"); 
          printf "%5.1f : %s\n", $2, proc[length(proc)] 
        };' |
    awk '
      NR==1 { 
      printf "%5s   %s\n%s\n", "CPU%", "PROCESS", $0 
    } 
    NR>1 { 
      printf "%s\n", $0 
    }'

elif [[ $1 == "--temp" ]]; then

  for i in {0..3}; do cat /sys/class/thermal/thermal_zone$i/temp; done | sort | tail -n 1 | awk '{printf "%.0f\n", $1/1000}'

else

  echo "Invalid argument"
  help
  exit 1

fi
