#!/usr/bin/env bash

source $(dirname $0)/common.sh
player=org.mpris.MediaPlayer2.playerctld

help() {
  echo "Usage: $0 [args]"
  echo "  --check: check if player is active [0 = active, 1 = inactive]"
  echo "  --next: next track"
  echo "  --prev: previous track"
  echo "  --show: write the metadata"
}

interpret_time() {
  min=$(echo "$1 / 60 / 1000000" | bc)
  sec=$(echo "$1 / 1000000 % 60" | bc)
  printf "%02d:%02d" "$min" "$sec"
}

roll() {
  len=${#1}
  tolen=$2
  if [ $len -le $tolen ]; then
    echo $1
  else
    delta=$(($len - $tolen))
    if [ $(($delta % 2)) -eq 0 ]; then
      delta=$(($delta + 1))
    fi
    lcrop=$((($(date +%s) % $delta - $delta / 2) * 2))
    lcrop=${lcrop#-}
    rcrop=$(($delta - $lcrop))
    if [ $lcrop -gt 0 ]; then
      lfill="…"
    else
      lfill=""
    fi
    if [ $rcrop -le 1 ]; then
      rfill=""
      rcrop=$len
    else
      rfill="…"
      rcrop=$((-$rcrop))
    fi
    echo $lfill${1:$lcrop:$rcrop}$rfill
  fi
}

trim() {
  read -r var
  echo "$var" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

update_metadata() {
  active_player=$(playerctl -l | grep "tidal" | tail -n 1)
  if [ -z "$active_player" ]; then
    echo "" >$TMPDIR/player_active
    echo "" >$TMPDIR/player_metadata
    echo "" >$TMPDIR/player_status
    echo "" >$TMPDIR/player_seek
  fi
  echo $active_player >$TMPDIR/player_active

  metadata=$(playerctl metadata)
  if [[ "$metadata" != "" ]]; then
    echo "$metadata" >$TMPDIR/player_metadata
  fi
  can_seek=$(qdbus org.mpris.MediaPlayer2.${active_player} /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.CanSeek)
  if [ "$can_seek" = "true" ]; then
    length=$(echo "$metadata" | grep -oP 'length\K.*$' | tr -d ' ')
    length=$(interpret_time "$length")
    position=$(qdbus org.mpris.MediaPlayer2.${active_player} /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Position)
    position=$(interpret_time "$position")
    seek="$position / $length"
  else
    seek=""
  fi
  echo $seek >$TMPDIR/player_seek

  status=$(qdbus org.mpris.MediaPlayer2.${active_player} /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus)
  if [[ "$status" != "" ]]; then
    echo $status >$TMPDIR/player_status
  fi
}

check_if_active() {
  player=$(cat $TMPDIR/player_active)
  metadata=$(cat $TMPDIR/player_metadata)
  if [ -z "$player" ] || [ -z "$metadata" ]; then
    echo 1
  else
    echo 0
  fi
}

render() {
  active_player=$(cat $TMPDIR/player_active)
  if [ -z "$active_player" ]; then
    exit 1
  else
    metadata=$(cat $TMPDIR/player_metadata)
    status=$(cat $TMPDIR/player_status)
    seek=$(cat $TMPDIR/player_seek)

    title=$(echo "$metadata" | grep -oP 'title\K.*$' | trim)
    artist=$(echo "$metadata" | grep -oP 'artist\K.*$' | trim)
    album=$(echo "$metadata" | grep -oP 'album\K.*$' | trim)

    title=$(echo "$title" | sed 's/\[.*\]//')

    if [[ $(hyprctl monitors -j | jq '.[0].name') != *"eDP"* ]]; then
      title_width=19
      artist_width=17
    else
      title_width=15
      artist_width=13
    fi

    if [[ $active_player == *"firefox"* ]]; then
      player_icon="<span color='#FF9530'>󰈹</span>"
    elif [[ $active_player == *"mpv"* ]]; then
      player_icon="<span color='#53205A'></span>"
    elif [[ $active_player == *"spotify"* ]]; then
      player_icon="<span color='#1CD762'></span>"
    elif [[ $active_player == *"vlc"* ]]; then
      player_icon="<span color='#FF8800'>󰕼</span>"
    elif [[ $active_player == *"tidal"* ]]; then
      player_icon="<span color='#b2b2b2'></span>"
    else
      player_icon=""
    fi

    if [ "$status" = "Playing" ]; then
      status_icon=""
    elif [ "$status" = "Paused" ]; then
      status_icon=""
    fi

    text=$(echo \
      "<tt><big>"$player_icon"</big></tt>" \
      "<big><sub>"$status_icon"</sub></big>" \
      $(roll "$title" $title_width) "|" $(roll "$artist" $artist_width))

    if [ -z "$album" ]; then
      tooltip_album=""
    else
      tooltip_album=$(echo -e "\n:: <i>$album</i>")
    fi

    tooltip=$(echo -e ".. $title $seek\n.: $artist$tooltip_album")

    jq -n -c --arg TEXT "$text" --arg TOOLTIP "$tooltip" \
      '{
          text: $TEXT,
          tooltip: $TOOLTIP,
          # class: $CLASS
        }'
  fi
}

update_metadata

if [[ "$1" == "--check" ]]; then

  exit $(check_if_active)

elif [[ "$1" == "--play-pause" ]]; then

  qdbus $player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause

elif [[ "$1" == "--next" ]]; then

  qdbus $player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

elif [[ "$1" == "--prev" ]]; then

  qdbus $player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous

elif [[ "$1" == "--show" ]]; then

  render

else

  echo "Invalid argument"
  help
  exit 1

fi
