import = [
"~/.config/alacritty/github_dark_high_contrast.toml", 
]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MonaspiceKr Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceKr Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceKr Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceKr Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[window]
opacity = 0.95
padding = { "x" = 10, "y" = 10 }
decorations = "None"
